FROM alpine
MAINTAINER Tobias Blomberg <sm0svx@svxlink.org>

# Install required packages and set up the svxlink user
RUN apk update
RUN apk add git cmake make g++ pkgconfig libsigc++-dev alsa-lib-dev opus-dev \
            speex-dev popt-dev libgcrypt-dev tcl-dev curl-dev gsm-dev \
            linux-headers groff curl librtlsdr-dev jsoncpp-dev nano \
            libogg-dev ladpsa-dev


# For debugging and development
ADD svxlink-sounds-en_US-heather-16k-18.03.1.tar.bz2 /usr/share/svxlink/sounds/
RUN ln -s en_US-heather-16k /usr/share/svxlink/sounds/en_US

# Add a svxlink user for running the build
ARG HOME=/home/svxlink
RUN adduser -u 10000 -h ${HOME} -D svxlink
USER svxlink


# Build SvxLink
WORKDIR ${HOME}
ARG GIT_REPO=https://github.com/F4HWD/svxlink-usrp-authkey.git
ARG GIT_REF=tetra-usrp
ARG GIT_SSL_NO_VERIFY=true
RUN git clone --branch ${GIT_REF} ${GIT_REPO}
RUN mkdir build
WORKDIR ${HOME}/build
RUN cmake -DDO_INSTALL_CHOWN=YES \
          -DDO_INSTALL_CHOWN=YES \
          ../svxlink/src
RUN make -j${NUM_CORES}

# Create an archive for the whole installation
USER root
RUN make install DESTDIR=/tmp/svxlink
RUN tar cvzf /tmp/svxlink.tar.gz . -C /tmp/svxlink

# Add an entrypoint to use for debugging and development
ADD entrypoint /
ENTRYPOINT ["/entrypoint"]

# vim: set filetype=dockerfile:
